spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_rental_db?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



